# Generated by Django 5.1.3 on 2024-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='address2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressbook',
            name='city',
            field=models.CharField(default='fortabbas', max_length=50),
            preserve_default=False,
        ),
    ]
