# Generated by Django 5.1.3 on 2024-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_addressbook_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='addressbook',
            name='address2',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='state',
            field=models.CharField(default='Punjab', max_length=50),
            preserve_default=False,
        ),
    ]
